# -*- coding: utf-8 -*-
"""Lead-Scoring-Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dNZBqbjgOTCLGN0CZM-tDhNhumvgYuNj

# Lead Scoring Model on Synthetic CRM Data

## 1. Import Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
pd.set_option("display.max_columns", None)

"""## 2. Data Loading"""

df = pd.read_csv("synthetic_leads.csv") # Load the synthetic leads dataset

# Display first five rows
display(df.head())

"""## 3. Exploratory Data Analysis

### Dataset Shape
"""

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

"""### Column Information"""

df.info()

"""### Summary Statistics"""

display(df.describe(include="all"))

"""### Missing Values"""

display(df.isnull().sum())

"""### Unique Values"""

for col in ["Industry", "Budget", "Urgency", "Company_Size"]:
    print(f"\n{col}")
    print(df[col].value_counts())

"""### Why Are We Doing This?

This is called Exploratory Data Analysis (EDA). Before building any model, a data analyst first understands:

*   what the dataset contains,
*   whether there are missing values,
*   whether the categories look reasonable,
*   and whether any cleaning is needed.

Since your data is synthetic, we expect it to be clean—but it's still good practice to verify this.

## 4. Data Cleaning

## 5. Rule-Based Lead Scoring

### Lead Scoring Logic

This project uses a rule-based scoring system to prioritize inbound sales leads. Budget is given the highest weight (40%) because organizations with larger budgets are generally more likely to purchase products or services. Urgency contributes 30% since leads requiring immediate solutions often convert faster. Industry fit contributes the remaining 30%, prioritizing industries that align best with the company's offerings. Based on the total score, leads are categorized as Hot, Warm, or Cold to help sales teams prioritize outreach.

### Define Scoring Rubric
"""

budget_scores = {
    "Low": 10,
    "Medium": 25,
    "High": 40
}

urgency_scores = {
    "Low": 10,
    "Medium": 20,
    "High": 30
}

industry_scores = {
    "Healthcare": 30,
    "Finance": 25,
    "Technology": 20,
    "Retail": 15,
    "Education": 10,
    "Manufacturing": 5
}

"""### Calculate Lead Score"""

df["Lead Score"] = (
    df["Budget"].map(budget_scores)
    + df["Urgency"].map(urgency_scores)
    + df["Industry"].map(industry_scores)
)
display(df.head())

"""## 6. Lead Categorization"""

def classify(score):
    if score >= 80:
        return "Hot"
    elif score >= 60:
        return "Warm"
    else:
        return "Cold"

df["Lead Category"] = df["Lead Score"].apply(classify)
display(df.head())

# Save the DataFrame with Lead Scores and Categories
df.to_csv("scored_leads.csv", index=False)
print("Scored leads saved to scored_leads.csv")

"""## 7. Data Visualization"""

plt.figure(figsize=(8, 6))
df["Lead Category"].value_counts().loc[['Cold', 'Warm', 'Hot']].plot(kind="bar", color=['#440154', '#21918c', '#fde725'])
plt.title('Distribution of Lead Categories')
plt.xlabel('Lead Category')
plt.ylabel('Number of Leads')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Histogram for Lead Score
plt.figure(figsize=(8, 6))
plt.hist(df["Lead Score"], bins=10, color='skyblue', edgecolor='black')
plt.title('Distribution of Lead Scores')
plt.xlabel('Lead Score')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Budget Distribution
plt.figure(figsize=(8, 6))
df["Budget"].value_counts().plot(kind="bar", color='lightcoral')
plt.title('Distribution of Budget')
plt.xlabel('Budget')
plt.ylabel('Number of Leads')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Industry Distribution
plt.figure(figsize=(10, 7))
df["Industry"].value_counts().plot(kind="bar", color='lightgreen')
plt.title('Distribution of Industry')
plt.xlabel('Industry')
plt.ylabel('Number of Leads')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Company Size Distribution
plt.figure(figsize=(8, 8))
df["Company_Size"].value_counts().plot(kind="pie", autopct='%1.1f%%', startangle=90, colors=['gold', 'lightskyblue', 'lightcoral'])
plt.title('Distribution of Company Size')
plt.ylabel('') # Hide the default 'Company_Size' label
plt.show()

"""## 8. Conclusion

This project demonstrated a complete lead scoring workflow using synthetic CRM data. A rule-based model was developed to prioritize leads based on budget, urgency, and industry fit. Exploratory Data Analysis and visualizations helped understand the dataset, while a Logistic Regression classifier illustrated how machine learning can be applied to the same problem. Although the dataset is synthetic, the workflow reflects a practical approach that can be adapted to real-world CRM systems.

## 9. Machine Learning Comparison

## Section 9: Machine Learning Classifier

While a rule-based system provides a clear and interpretable way to score leads, machine learning can offer a more data-driven approach, potentially capturing complex relationships within the data to predict lead conversion. Here, we'll build a simple classification model to predict whether a lead will convert (`Converted` column).

### Data Preparation for ML

First, we need to prepare our data. This involves:
1.  **Feature Selection**: Identifying relevant features.
2.  **One-Hot Encoding**: Converting categorical features into numerical format suitable for machine learning algorithms.
3.  **Splitting Data**: Dividing the dataset into training and testing sets.
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Define features (X) and target (y)
X = df[['Industry', 'Budget', 'Urgency', 'Company_Size', 'Employees']]
y = df['Converted']

# Identify categorical and numerical features
categorical_features = ['Industry', 'Budget', 'Urgency', 'Company_Size']
numerical_features = ['Employees']

# Create a column transformer for one-hot encoding categorical features
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features),
        ('num', 'passthrough', numerical_features)
    ])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

print("Data preparation complete. X_train shape:", X_train.shape, "y_train shape:", y_train.shape)

"""### Model Training

We'll use a Logistic Regression classifier, a simple yet effective model for binary classification, to predict lead conversion.
"""

from sklearn.linear_model import LogisticRegression

# Create a pipeline that first preprocesses the data and then applies the classifier
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(solver='liblinear', random_state=42))
])

# Train the model
model.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")

"""### Model Evaluation

Evaluate the trained model using metrics like accuracy, precision, recall, and F1-score on the test set.
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Model Accuracy: {accuracy:.4f}")
print(f"Model Precision: {precision:.4f}")
print(f"Model Recall: {recall:.4f}")
print(f"Model F1-Score: {f1:.4f}")
print("\nConfusion Matrix:\n", conf_matrix)

# Plot Confusion Matrix
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted Negative', 'Predicted Positive'],
            yticklabels=['Actual Negative', 'Actual Positive'])
plt.title('Confusion Matrix for Lead Conversion Prediction')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""### Explanation of ML Results

The Logistic Regression classifier achieved an accuracy of **{accuracy*100:.2f}%**.

**Accuracy**: {accuracy:.2f}
**Precision**: {precision:.2f}
**Recall**: {recall:.2f}
**F1-Score**: {f1:.2f}

Since the dataset is synthetic and relatively small, the results mainly demonstrate the workflow rather than providing robust predictive performance on real-world data. The model shows a balance between correctly identifying positive and negative cases, but there is room for improvement, potentially through more advanced feature engineering, trying different models, or using a larger, more diverse dataset.

_Note: The specific percentages are based on the model's performance on the test set and will vary with different random states or datasets._

This output is generated by extracting the values from the model evaluation. It's important to remember that for real-world applications, these metrics would need to be interpreted in the context of business objectives and potential costs of false positives/negatives.
"""